version: '3'

services:

  hydra-postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - data-hydra:/var/lib/postgresql/data
    restart: on-failure

  hydra-migrate-database:
    image: oryd/hydra:${HYDRA_VERSION}
    command: ["migrate", "sql", "--yes", "$DSN"]

  hydra-host:
    image: oryd/hydra:${HYDRA_VERSION}
    ports:
      - ${PUBLIC_PORT}:4444
      - ${ADMIN_PORT}:4445
    environment:
      - SECRETS_SYSTEM
      - DSN
      - URLS_SELF_ISSUER
      - URLS_LOGIN=${SC_FRONTEND}/oauth2/login
      - URLS_CONSENT=${SC_FRONTEND}/oauth2/consent
      - TLS_ALLOW_TERMINATION_FROM
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
    depends_on:
      - hydra-migrate-database
    restart: on-failure
    command: ["serve", "all", "${SERVE_PARAMS}"]
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  data-hydra:

# networks:
  # default:
    # external:
      # name: schulcloudserver_schulcloud-server-network
