version: '3'

services:

  hydra-postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - data-hydra:/var/lib/postgresql/data

  hydra-migrate-database:
    image: oryd/hydra:${HYDRA_VERSION}
    environment:
        - DATABASE_URL
    command: ["migrate", "sql", "$DATABASE_URL"]

  hydra-host:
    image: oryd/hydra:${HYDRA_VERSION}
    ports:
      - ${PUBLIC_PORT}:4444
      - ${ADMIN_PORT}:4445
    environment:
      - SYSTEM_SECRET
      - DATABASE_URL
      - OAUTH2_ISSUER_URL
      - OAUTH2_CONSENT_URL=${SC_FRONTEND}/oauth2/consent
      - OAUTH2_LOGIN_URL=${SC_FRONTEND}/oauth2/login
      - HTTPS_ALLOW_TERMINATION_FROM
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT
    depends_on:
      - hydra-migrate-database
    restart: on-failure
    command: ["serve", "all", "${SERVE_PARAMS}"]

volumes:
  data-hydra:

# networks:
  # default:
    # external:
      # name: schulcloudserver_schulcloud-server-network